#Author: Jose Carlos Fernandes e F Filho <joselgn@gmail.com>
#version: '3'

#Banco de Dados
db:
  image: mariadb
  container_name: mariaDB
  ports:
      - "3306:3306"
  environment:
     MYSQL_ROOT_PASSWORD: root  
     MYSQL_DATABASE: lojavirtualdb
  volumes:
     - ./mariadb/bd:/home/bd
     - ./mariadb/backup:/home/bkp 

#Aplicação
lojavirtual-docker:
  image: lojavirtual-img
  container_name: lojavirtual-docker
  ports:
     - "8081:80"
  volumes:
    - ./codigo:/var/www/html
  links:
     - db:db
  #depends_on:
   #  - db
  #command: "cd /var/www/html && php artisan migrate"
